#!/usr/bin/env bash
# Aliases

## Shorts
alias ..='cd ..'
alias aws-e='printenv | grep AWS'
alias aws-lp='cat ~/.aws/credentials | grep "\[" | tr -d "[]" | sort'
alias cd-dot='cd "$(dirname $(readlink ~/.bashrc_ext))"'
alias cmo='cd "${HOME}/oss/github.com/${USER}"'
alias my-pip4='dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com | tr -d "\""'	# See https://coderwall.com/p/lyrjsq/extract-your-external-ip-using-command-line-tools
alias my-pip6='dig -6 TXT +short o-o.myaddr.l.google.com @ns1.google.com | tr -d "\""'	# See https://coderwall.com/p/lyrjsq/extract-your-external-ip-using-command-line-tools
alias show-paths="echo \${PATH} | tr ':' '\n'"
alias xclip='xclip -selection c'

## Docker
alias dock-img-sz="docker images --format '{{.Size}}\t{{.Repository}}:{{.Tag}}\t{{.ID}}' | sort -h | column -t"

## git
alias g=git
alias gti=git

## k8s
alias k=kubectl
alias k-n-p="kubectl get pods -A -o json | jq -r '.items[] | .spec.nodeName + \"\t\" + .metadata.name' | sort"
alias k-a-p-f='kubectl port-forward -n argocd svc/argocd-server 8080:80'
alias k-n-p-c="kubectl get nodes -o json | jq -r '.items[] | .metadata.name + \"\t\" + .status.capacity.pods'"
alias k-p-c='echo ${KUBECONFIG}'
alias u-e-k-c=update-eks-kubeconfig

# Helpers
alias pa='echo A B C D E F G H I J K L M N O P Q R S T U V W X Y Z'
